services:
  # Main API Service
  - type: web
    name: reporder-api
    env: node
    region: oregon
    plan: free  # Change to 'starter' or higher for production
    buildCommand: npm install && cd services/api && npm install --include=dev && npm run build
    startCommand: cd services/api && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false  # You'll set this in Render dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_SCOPES
        value: read_products,read_inventory,read_locations
      - key: APP_URL
        sync: false  # Will be your Render URL
      - key: REDIS_HOST
        fromService:
          type: redis
          name: reporder-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: reporder-redis
          property: port
      - key: REDIS_PASSWORD
        sync: false  # Set manually from Redis dashboard after creation

  # Redis for BullMQ queues
  - type: redis
    name: reporder-redis
    region: oregon
    plan: free  # Free tier includes 25MB storage
    maxmemoryPolicy: noeviction
    ipAllowList: []  # Empty means only accessible from your Render services

